# -*- coding: utf-8 -*-
"""DATA_VORTEX_R3_News_Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5tj8k6y6j4alI1Fy4U6ydqf4N6ahOxY
"""

# Install the libraries needed for news collection and analysis
!pip -q install feedparser pandas matplotlib

#Collect news from Google News RSS
import feedparser
import pandas as pd
from datetime import datetime, timezone
from urllib.parse import quote

# Define the topics related to our project
topics = {
    "cybercrime": '"cybercrime" OR "online fraud" OR "digital scam"',
    "digital_exclusion": '"digital exclusion" OR "digital divide" OR "internet access"'
}

# Create an empty list to store the collected news articles
rows = []

# Collect news articles for each topic
for category, query in topics.items():

    # Create the Google News RSS search URL
    url = (
        "https://news.google.com/rss/search?q="
        + quote(query)
        + "&hl=en-IN&gl=IN&ceid=IN:en"
    )

    # Read the RSS feed
    feed = feedparser.parse(url)

    # Store the available details of each article
    for entry in feed.entries:
        rows.append({
            "title": entry.get("title", ""),
            "summary": entry.get("summary", ""),
            "url": entry.get("link", ""),
            "published_at": entry.get("published", ""),
            "collected_at": datetime.now(timezone.utc).isoformat(),
            "source": entry.get("source", {}).get("title", ""),
            "search_category": category
        })

# Convert the collected articles into a DataFrame
df = pd.DataFrame(rows)

# Display the number of articles collected
print("Total articles collected:", len(df))

# Display the first five rows
df.head()

# Save the collected news articles as a CSV file
filename = "DATA_VORTEX_R3_news_dataset_2.csv"

df.to_csv(filename, index=False, encoding="utf-8-sig")

# Display the file name and number of rows
print("CSV saved:", filename)
print("Rows:", len(df))

from datetime import datetime, timezone
from pathlib import Path

# Define the output directory
OUT = Path("/content")
OUT.mkdir(exist_ok=True)

run_time = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
snapshot_path = OUT / f"news_snapshot_{run_time}.csv"

# Use 'df' instead of 'news_df'
df.to_csv(snapshot_path, index=False)

print("Snapshot saved:", snapshot_path)
print("Snapshot rows:", len(df))
print("Collection time (UTC):", run_time)

# Display the number of articles before cleaning
print("Before cleaning:", len(df))

# Remove duplicate articles using their URLs
df = df.drop_duplicates(subset=["url"])

# Remove rows that do not have a title
df = df.dropna(subset=["title"])

# Clean the title and summary text
df["title"] = df["title"].astype(str).str.strip()
df["summary"] = df["summary"].fillna("").astype(str)

# Remove articles with empty titles
df = df[df["title"] != ""]

# Display the number of articles after cleaning
print("After cleaning:", len(df))

# Display the cleaned dataset
df.head()

# Create a timestamp for this data collection
snapshot_time = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")

# Create a file name using the collection timestamp
snapshot_file = f"news_snapshot_{snapshot_time}.csv"

# Save the current dataset as a snapshot
df.to_csv(snapshot_file, index=False, encoding="utf-8-sig")

# Display the snapshot details
print("Snapshot saved:", snapshot_file)
print("Snapshot time (UTC):", snapshot_time)

# Display the total number of collected articles
print("Total rows:", len(df))

# Count articles in each search category
print("\nCategories:")
print(df["search_category"].value_counts())

# Check for missing values in each column
print("\nMissing values:")
print(df.isnull().sum())

# Display the publication date range available in the dataset
print("\nDate range:")
print("Earliest published:", df["published_at"].min())
print("Latest published:", df["published_at"].max())

# Save the cleaned dataset for further analysis
df.to_csv(
    "DATA_VORTEX_R3_news_dataset_clean.csv",
    index=False,
    encoding="utf-8-sig"
)

# Confirm that the cleaned dataset is ready
print("Clean dataset ready!")

import zipfile
from pathlib import Path

# Use exact filename with spaces as uploaded in Colab
zip_path = Path("/content/DATA VORTEX ROUND 2.zip")

# Extract the ZIP file into a new folder
extract_folder = Path("/content/round2_files")
extract_folder.mkdir(exist_ok=True)

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_folder)

# Display the extracted files
for file in extract_folder.rglob("*"):
    if file.is_file():
        print(file.name)

# Import joblib to load the saved machine learning models
import joblib
from pathlib import Path

# Find the folder containing the Round 2 model files
model_folder = (
    Path("/content/round2_files")
    / "DATA VORTEX ROUND 2"
)

# Load the trained sentiment and topic models
sentiment_model = joblib.load(
    model_folder / "sentiment_model.pkl"
)

topic_model = joblib.load(
    model_folder / "topic_model.pkl"
)

# Confirm that both models are loaded
print("Sentiment model loaded:", type(sentiment_model))
print("Topic model loaded:", type(topic_model))

# Make a copy so the original collected data stays unchanged
df = df.copy()

# Check that the required columns are available
print("Available columns:", df.columns.tolist())

# Fill missing titles and summaries with empty text
df["title"] = df["title"].fillna("").astype(str)
df["summary"] = df["summary"].fillna("").astype(str)

# Combine the title and summary into one text column
df["analysis_text"] = (
    df["title"] + " " + df["summary"]
).str.strip()

# Remove rows that do not contain any text
df = df[df["analysis_text"] != ""].copy()

# Show a few examples
display(df[["title", "summary", "analysis_text"]].head())

# Run the saved Round 2 models on the collected news text
df["sentiment_prediction"] = sentiment_model.predict(
    df["analysis_text"]
)

df["topic_prediction"] = topic_model.predict(
    df["analysis_text"]
)

# Display the predictions for a few articles
display(
    df[
        [
            "title",
            "sentiment_prediction",
            "topic_prediction"
        ]
    ].head(10)
)

# Count how many articles received each sentiment label
print("Sentiment prediction counts:")
print(df["sentiment_prediction"].value_counts(dropna=False))

# Count how many articles received each topic label
print("\nTopic prediction counts:")
print(df["topic_prediction"].value_counts(dropna=False))

# Check the total number of analyzed articles
print("\nTotal analyzed articles:", len(df))

# Save the analyzed data as a CSV file
output_file = "/content/round3_analyzed_news.csv"

df.to_csv(output_file, index=False)

# Confirm where the file was saved
print("Analyzed dataset saved to:", output_file)

# Import libraries for making charts
import matplotlib.pyplot as plt

# Count sentiment predictions
sentiment_counts = df["sentiment_prediction"].value_counts()

# Create the sentiment chart
plt.figure(figsize=(8, 5))
sentiment_counts.plot(kind="bar")

plt.title("Sentiment Distribution of Collected News")
plt.xlabel("Predicted Sentiment")
plt.ylabel("Number of Articles")
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()

# Count topic predictions
topic_counts = df["topic_prediction"].value_counts()

# Create the topic chart
plt.figure(figsize=(9, 5))
topic_counts.plot(kind="bar")

plt.title("Topic Category Distribution")
plt.xlabel("Predicted Topic")
plt.ylabel("Number of Articles")
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.show()

# Display all available columns
print("Dataset columns:")
print(df.columns.tolist())

# Check whether timestamp columns are available
time_columns = [
    column for column in df.columns
    if "date" in column.lower()
    or "time" in column.lower()
    or "published" in column.lower()
    or "collected" in column.lower()
]

print("\nPossible time columns:")
print(time_columns)

# Show a few timestamp values
for column in time_columns:
    print(f"\n{column}:")
    print(df[column].head())

# Calculate the number and percentage of each predicted sentiment
sentiment_summary = (
    df["sentiment_prediction"]
    .value_counts()
    .rename_axis("Predicted Sentiment")
    .reset_index(name="Article Count")
)

sentiment_summary["Percentage"] = (
    sentiment_summary["Article Count"] / len(df) * 100
).round(1)

# Display the summary for the report
display(sentiment_summary)

# Check the topic labels used by the saved Round 2 model
print("Topic model classes:")

if hasattr(topic_model, "classes_"):
    print(topic_model.classes_)

elif hasattr(topic_model, "named_steps"):
    # Find the classifier inside the saved pipeline
    for step_name, step_model in topic_model.named_steps.items():
        if hasattr(step_model, "classes_"):
            print(step_name, ":", step_model.classes_)

else:
    print("Could not find class labels automatically.")

# Select the first 20 articles for manual review
review_columns = [
    "title",
    "summary",
    "sentiment_prediction",
    "topic_prediction"
]

review_sample = df[review_columns].head(20).copy()

# Add columns for human review
review_sample["Manual Sentiment"] = ""
review_sample["Manual Cybercrime Topic"] = ""
review_sample["Notes"] = ""

# Display the sample
display(review_sample)

# Save the sample as a CSV file
review_sample.to_csv(
    "/content/manual_review_sample.csv",
    index=False
)

print("Manual review sample saved.")

import re

# Define keywords for exploratory topic tagging
topic_keywords = {
    "Online_Fraud": [
        "online fraud", "cyber fraud",
        "online scam", "digital scam"
    ],
    "Phishing": [
        "phishing", "fake link", "spoofing"
    ],
    "Cybercrime": [
        "cybercrime", "cyber crime",
        "hacking", "data breach", "ransomware"
    ],
    "Digital_Exclusion": [
        "digital divide", "digital exclusion",
        "internet access", "digital literacy"
    ]
}

# Match keywords in the article text
def find_topic_tags(text):
    text = str(text).lower()
    matched_topics = []

    for topic, keywords in topic_keywords.items():
        for keyword in keywords:
            if re.search(
                r"\b" + re.escape(keyword) + r"\b",
                text
            ):
                matched_topics.append(topic)
                break

    if not matched_topics:
        matched_topics.append("No_Keyword_Match")

    return ", ".join(matched_topics)

# Apply the keyword rules to the dataset
df["exploratory_topic_tags"] = df["analysis_text"].apply(
    find_topic_tags
)

# Count all matching tags
tag_counts = (
    df["exploratory_topic_tags"]
    .str.split(", ")
    .explode()
    .value_counts()
)

print("Exploratory keyword tag counts:")
print(tag_counts)

import re

# Define keywords for exploratory topic tagging
topic_keywords = {
    "Online_Fraud": [
        "online fraud", "cyber fraud",
        "online scam", "digital scam"
    ],
    "Phishing": [
        "phishing", "fake link", "spoofing"
    ],
    "Account_Security": [
        "account security", "account hacked",
        "password theft", "identity theft"
    ],
    "Cybercrime": [
        "cybercrime", "cyber crime",
        "hacking", "data breach", "ransomware"
    ],
    "Digital_Exclusion": [
        "digital divide", "digital exclusion",
        "internet access", "digital literacy"
    ]
}

# Find topic keywords in each article
def find_topic_tags(text):
    text = str(text).lower()
    matched_topics = []

    for topic, keywords in topic_keywords.items():
        for keyword in keywords:
            if re.search(
                r"\b" + re.escape(keyword) + r"\b",
                text
            ):
                matched_topics.append(topic)
                break

    # Mark articles that have no matching keywords
    if not matched_topics:
        matched_topics.append("No_Keyword_Match")

    return ", ".join(matched_topics)

# Apply keyword tagging to the article text
df["exploratory_topic_tags"] = df["analysis_text"].apply(
    find_topic_tags
)

# Count all topic tags
tag_counts = (
    df["exploratory_topic_tags"]
    .str.split(", ")
    .explode()
    .value_counts()
)

print("Exploratory topic tag counts:")
print(tag_counts)

# Check which columns are available in the dataset
print("All dataset columns:")
print(df.columns.tolist())

# Find columns that may contain dates or timestamps
time_columns = [
    column for column in df.columns
    if any(word in column.lower() for word in [
        "date", "time", "published", "collected"
    ])
]

print("\nPossible timestamp columns:")
print(time_columns)

# Display sample values from each timestamp column
for column in time_columns:
    print(f"\nSample values from {column}:")
    print(df[column].head())

# Save the dataset with model predictions and keyword tags
output_file = "/content/round3_analyzed_news.csv"

df.to_csv(output_file, index=False)

print("Updated dataset saved to:", output_file)

import pandas as pd

# Convert publication and collection timestamps into datetime format
df["published_at"] = pd.to_datetime(
    df["published_at"],
    errors="coerce",
    utc=True
)

df["collected_at"] = pd.to_datetime(
    df["collected_at"],
    errors="coerce",
    utc=True
)

# Check how many timestamps were successfully parsed
print("Valid publication dates:", df["published_at"].notna().sum())
print("Valid collection dates:", df["collected_at"].notna().sum())

# Display the earliest and latest publication dates
print("\nEarliest publication date:", df["published_at"].min())
print("Latest publication date:", df["published_at"].max())

# Check how many different collection times are present
print(
    "\nUnique collection timestamps:",
    df["collected_at"].nunique()
)

# Convert publication date to datetime and group by date & sentiment
df["date"] = pd.to_datetime(df["published_at"]).dt.date
daily_sentiment = df.groupby(["date", "sentiment_prediction"]).size().unstack(fill_value=0)

# Calculate percentage if needed
daily_percent = daily_sentiment.div(daily_sentiment.sum(axis=1), axis=0) * 100

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Convert the date index into datetime format
daily_sentiment.index = pd.to_datetime(
    daily_sentiment.index
)

# Sort dates in chronological order
daily_sentiment = daily_sentiment.sort_index()

# Create the first chart with readable date labels
fig, ax = plt.subplots(figsize=(14, 6))

daily_sentiment.plot(
    kind="bar",
    ax=ax,
    width=0.8
)

# Show fewer date labels to avoid overlapping
tick_positions = range(0, len(daily_sentiment), 7)
ax.set_xticks(list(tick_positions))

# Format the displayed dates
ax.set_xticklabels(
    daily_sentiment.index[::7].strftime("%d %b"),
    rotation=45,
    ha="right"
)

ax.set_title("Predicted Sentiment by Publication Date")
ax.set_xlabel("Publication Date (UTC)")
ax.set_ylabel("Number of Articles")

plt.tight_layout()
plt.show()


# Calculate daily sentiment percentages
daily_percent = daily_sentiment.div(
    daily_sentiment.sum(axis=1),
    axis=0
) * 100

# Create the percentage chart
fig, ax = plt.subplots(figsize=(14, 6))

daily_percent.plot(
    kind="bar",
    ax=ax,
    width=0.8
)

# Show one date label every seven days
ax.set_xticks(list(tick_positions))

ax.set_xticklabels(
    daily_percent.index[::7].strftime("%d %b"),
    rotation=45,
    ha="right"
)

ax.set_title("Daily Sentiment Percentage by Publication Date")
ax.set_xlabel("Publication Date (UTC)")
ax.set_ylabel("Percentage of Articles")

plt.tight_layout()
plt.show()

# Make sure the publication date column is in datetime format
df["published_at"] = pd.to_datetime(
    df["published_at"],
    errors="coerce",
    utc=True
)

# Keep rows with valid publication dates
weekly_df = df.dropna(subset=["published_at"]).copy()

# Group publication dates by week
weekly_df["week"] = (
    weekly_df["published_at"]
    .dt.to_period("W")
    .astype(str)
)

# Count predicted sentiments for each week
weekly_sentiment = pd.crosstab(
    weekly_df["week"],
    weekly_df["sentiment_prediction"]
)

# Show the weekly counts
display(weekly_sentiment)

# Plot weekly sentiment counts
ax = weekly_sentiment.plot(
    kind="bar",
    figsize=(12, 6),
    width=0.8
)

ax.set_title("Weekly Sentiment Distribution")
ax.set_xlabel("Publication Week")
ax.set_ylabel("Number of Articles")
ax.tick_params(axis="x", rotation=35)

plt.tight_layout()
plt.show()

# Convert weekly counts into percentages
weekly_percent = weekly_sentiment.div(
    weekly_sentiment.sum(axis=1),
    axis=0
) * 100

# Display the weekly percentages
display(weekly_percent.round(1))

# Plot weekly sentiment percentages
ax = weekly_percent.plot(
    kind="bar",
    figsize=(12, 6),
    width=0.8
)

ax.set_title("Weekly Sentiment Percentage")
ax.set_xlabel("Publication Week")
ax.set_ylabel("Percentage of Articles")
ax.tick_params(axis="x", rotation=35)

plt.tight_layout()
plt.show()

# Convert publication dates safely
df["published_at"] = pd.to_datetime(
    df["published_at"],
    errors="coerce",
    utc=True
)

# Find dates before 1970
old_dates = df[
    df["published_at"] < "1970-01-01"
]

# Display suspicious records for inspection
display(
    old_dates[
        ["title", "published_at", "url"]
    ]
)

print("Suspicious records:", len(old_dates))

# Keep only valid publication dates
weekly_df = df.dropna(
    subset=["published_at"]
).copy()

# Remove dates before 1970 only after checking Step 32
weekly_df = weekly_df[
    weekly_df["published_at"] >= "1970-01-01"
].copy()

# Convert timestamps directly into weekly periods
weekly_df["week"] = (
    weekly_df["published_at"]
    .dt.tz_convert(None)
    .dt.to_period("W")
)

# Count predicted sentiments for each week
weekly_clean = pd.crosstab(
    weekly_df["week"],
    weekly_df["sentiment_prediction"]
)

# Display the corrected weekly table
display(weekly_clean)

# Calculate weekly sentiment percentages
weekly_percent = weekly_clean.div(
    weekly_clean.sum(axis=1),
    axis=0
) * 100

# Create the chart
fig, ax = plt.subplots(figsize=(12, 6))

weekly_percent.plot(
    kind="bar",
    ax=ax,
    width=0.8
)

# Display fewer date labels
step = max(1, len(weekly_percent) // 12)
positions = list(range(0, len(weekly_percent), step))

ax.set_xticks(positions)
ax.set_xticklabels(
    [str(weekly_percent.index[i]) for i in positions],
    rotation=45,
    ha="right"
)

ax.set_title("Weekly Predicted Sentiment Percentage")
ax.set_xlabel("Publication Week")
ax.set_ylabel("Percentage of Articles")

plt.tight_layout()
plt.show()

# Make a fresh copy of the dataset
weekly_df = df.copy()

# Keep only rows with valid publication dates
weekly_df = weekly_df.dropna(
    subset=["published_at"]
).copy()

# Remove timezone information before weekly grouping
weekly_df["published_at"] = (
    weekly_df["published_at"].dt.tz_convert(None)
)

# Create weekly periods directly from timestamps
weekly_df["week"] = (
    weekly_df["published_at"].dt.to_period("W")
)

# Count predicted sentiments for each week
weekly_clean = pd.crosstab(
    weekly_df["week"],
    weekly_df["sentiment_prediction"]
)

# Display the first and last weeks
print("First weeks:")
display(weekly_clean.head())

print("Latest weeks:")
display(weekly_clean.tail())

# Check the earliest and latest week
print("Earliest week:", weekly_clean.index.min())
print("Latest week:", weekly_clean.index.max())

# Save weekly sentiment counts for the report
weekly_clean.to_csv(
    "/content/round3_weekly_sentiment.csv"
)

print("Weekly sentiment table saved.")

# Check the current date column and its earliest values
print("Date column type:", df["published_at"].dtype)
print("Earliest published date:", df["published_at"].min())
print("Latest published date:", df["published_at"].max())

# Show records around the suspicious date
print("\nRecords before 1970:")
display(df.loc[df["published_at"] < pd.Timestamp("1970-01-01", tz="UTC"),
               ["title", "published_at"]])

# Check how many dates are missing
print("\nMissing published dates:", df["published_at"].isna().sum())

# Create a fresh copy for weekly analysis
weekly_df = df.copy()

# Keep records with valid publication dates
weekly_df = weekly_df.dropna(subset=["published_at"]).copy()

# Make sure the dates are in UTC
weekly_df["published_at"] = pd.to_datetime(
    weekly_df["published_at"], errors="coerce", utc=True
)

# Remove any dates that could not be parsed
weekly_df = weekly_df.dropna(subset=["published_at"]).copy()

# Group articles by publication week and predicted sentiment
weekly_df["week"] = (
    weekly_df["published_at"]
    .dt.tz_convert(None)
    .dt.to_period("W")
)

weekly_clean = pd.crosstab(
    weekly_df["week"],
    weekly_df["sentiment_prediction"]
)

# Display the first and last weeks
display(weekly_clean.head())
display(weekly_clean.tail())

print("Earliest week:", weekly_clean.index.min())
print("Latest week:", weekly_clean.index.max())

# Check the earliest and latest publication dates
print("Date type:", df["published_at"].dtype)
print("Earliest date:", df["published_at"].min())
print("Latest date:", df["published_at"].max())

# Show records from before 1970
old_dates = df[
    df["published_at"] < pd.Timestamp("1970-01-01", tz="UTC")
]

print("Records before 1970:", len(old_dates))
display(old_dates[["title", "published_at"]])

# Create a fresh copy for weekly analysis
weekly_df = df.copy()

# Keep valid publication dates
weekly_df = weekly_df.dropna(subset=["published_at"]).copy()

# Convert dates to UTC datetime
weekly_df["published_at"] = pd.to_datetime(
    weekly_df["published_at"], errors="coerce", utc=True
)

# Remove dates that could not be parsed
weekly_df = weekly_df.dropna(subset=["published_at"]).copy()

# Create weekly periods
weekly_df["week"] = (
    weekly_df["published_at"]
    .dt.tz_convert(None)
    .dt.to_period("W")
)

# Count predicted sentiments for each week
weekly_clean = pd.crosstab(
    weekly_df["week"],
    weekly_df["sentiment_prediction"]
)

# Display the refreshed weekly table
display(weekly_clean)

print("Earliest week:", weekly_clean.index.min())
print("Latest week:", weekly_clean.index.max())

# Create a fresh weekly analysis copy
weekly_df = df.copy()

# Convert publication dates to UTC
weekly_df["published_at"] = pd.to_datetime(
    weekly_df["published_at"], errors="coerce", utc=True
)

# Remove invalid dates
weekly_df = weekly_df.dropna(subset=["published_at"]).copy()

# Create weekly groups
weekly_df["week"] = (
    weekly_df["published_at"]
    .dt.tz_convert(None)
    .dt.to_period("W")
)

# Count sentiment predictions by week
weekly_clean = pd.crosstab(
    weekly_df["week"],
    weekly_df["sentiment_prediction"]
)

# Remove any week before 1970, if present
weekly_clean = weekly_clean[
    weekly_clean.index >= pd.Period("1970-01-01", freq="W")
]

# Show the cleaned table
display(weekly_clean.head())
display(weekly_clean.tail())

print("Earliest week:", weekly_clean.index.min())
print("Latest week:", weekly_clean.index.max())

# Save the cleaned weekly sentiment table
weekly_clean.to_csv("/content/round3_weekly_sentiment.csv")

print("Clean weekly sentiment CSV saved.")

# Make a copy for daily activity analysis
activity_df = df.copy()

# Convert publication dates to UTC
activity_df["published_at"] = pd.to_datetime(
    activity_df["published_at"], errors="coerce", utc=True
)

# Remove rows with invalid publication dates
activity_df = activity_df.dropna(subset=["published_at"]).copy()

# Extract the publication date
activity_df["publication_date"] = (
    activity_df["published_at"].dt.date
)

# Count articles published each day
daily_activity = (
    activity_df.groupby("publication_date")
    .size()
    .reset_index(name="article_count")
)

# Sort dates from oldest to newest
daily_activity = daily_activity.sort_values("publication_date")

# Display the daily article counts
display(daily_activity)

# Show the date with the highest article count
if not daily_activity.empty:
    busiest_day = daily_activity.loc[
        daily_activity["article_count"].idxmax()
    ]
    print("Busiest publication date:", busiest_day["publication_date"])
    print("Articles published:", busiest_day["article_count"])

# Save daily article activity
daily_activity.to_csv(
    "/content/round3_daily_activity.csv",
    index=False
)

print("Daily activity CSV saved.")

# Convert collection timestamps to UTC
df["collected_at"] = pd.to_datetime(
    df["collected_at"], errors="coerce", utc=True
)

# Show collection time range
print("First collection time:", df["collected_at"].min())
print("Last collection time:", df["collected_at"].max())

# Count distinct collection timestamps
print(
    "Unique collection timestamps:",
    df["collected_at"].nunique()
)

# Group article collection times by minute
df["collected_at"] = pd.to_datetime(
    df["collected_at"], errors="coerce", utc=True
)

df["collection_minute"] = df["collected_at"].dt.floor("min")

collection_batches = (
    df.groupby("collection_minute")
    .size()
    .reset_index(name="article_count")
)

display(collection_batches)

print("Collection batches:", len(collection_batches))
print("Total articles:", len(df))

# Count sentiment predictions
sentiment_summary = (
    df["sentiment_prediction"]
    .value_counts()
    .rename_axis("sentiment")
    .reset_index(name="article_count")
)

# Count topic predictions
topic_summary = (
    df["topic_prediction"]
    .value_counts()
    .rename_axis("topic")
    .reset_index(name="article_count")
)

# Count exploratory keyword tags
keyword_summary = (
    df["exploratory_topic_tags"]
    .value_counts()
    .rename_axis("keyword_tag")
    .reset_index(name="article_count")
)

print("Sentiment summary:")
display(sentiment_summary)

print("Topic summary:")
display(topic_summary)

print("Keyword tag summary:")
display(keyword_summary)

# Save sentiment summary
sentiment_summary.to_csv(
    "/content/round3_sentiment_summary.csv",
    index=False
)

# Save topic summary
topic_summary.to_csv(
    "/content/round3_topic_summary.csv",
    index=False
)

# Save keyword summary
keyword_summary.to_csv(
    "/content/round3_keyword_summary.csv",
    index=False
)

# Save collection batch summary
collection_batches.to_csv(
    "/content/round3_collection_batches.csv",
    index=False
)

print("All summary CSV files saved.")

# Count collection timestamps by minute
print("Unique collection minutes:",
      df["collected_at"].dt.floor("min").nunique())

# Show the collection time range
print("First collection:",
      df["collected_at"].min())

print("Last collection:",
      df["collected_at"].max())

# Inspect records with the earliest publication date
earliest_date = df["published_at"].min()

print("Earliest date:", earliest_date)

display(
    df.loc[
        df["published_at"] == earliest_date,
        ["title", "published_at", "source", "url"]
    ]
)

# Inspect the original date values for the affected articles
bad_date_rows = df[
    df["published_at"] == pd.Timestamp("1970-01-01", tz="UTC")
]

display(
    bad_date_rows[
        ["title", "published_at", "url", "source"]
    ]
)

# Count articles collected from each news source
source_summary = (
    df["source"]
    .value_counts()
    .rename_axis("source")
    .reset_index(name="article_count")
)

# Display the source-wise summary
display(source_summary)

# Show how many unique sources are present
print("Number of news sources:", df["source"].nunique())

# Save the source-wise article counts
source_summary.to_csv(
    "/content/round3_source_summary.csv",
    index=False
)

print("Source summary CSV saved.")

# Check duplicate articles using URL and title

print("Total articles:", len(df))

# Count duplicate URLs
duplicate_urls = df["url"].duplicated().sum()
print("Duplicate URLs:", duplicate_urls)

# Count duplicate titles
duplicate_titles = df["title"].duplicated().sum()
print("Duplicate titles:", duplicate_titles)

# Show duplicate rows for inspection
duplicates = df[
    df["url"].duplicated(keep=False) |
    df["title"].duplicated(keep=False)
]

print("Rows involved in duplicates:", len(duplicates))
display(duplicates[["title", "source", "published_at", "url"]].head(20))

# Save duplicate-check output
duplicates.to_csv("/content/round3_duplicates_check.csv", index=False)
print("Saved: /content/round3_duplicates_check.csv")

# Inspect articles with suspicious 1970 publication dates

df["published_at"] = pd.to_datetime(
    df["published_at"], errors="coerce", utc=True
)

suspicious = df[
    df["published_at"] < "2000-01-01"
]

print("Suspicious date rows:", len(suspicious))

display(
    suspicious[
        ["title", "source", "published_at", "collected_at", "url"]
    ]
)

suspicious.to_csv(
    "/content/round3_suspicious_dates.csv",
    index=False
)

print("Saved: /content/round3_suspicious_dates.csv")

# Recheck sentiment counts from the final analyzed dataset

print("Total rows:", len(df))

sentiment_counts = df["sentiment_prediction"].value_counts()
display(sentiment_counts)

sentiment_counts.to_csv(
    "/content/round3_final_sentiment_counts.csv"
)

print("Saved: /content/round3_final_sentiment_counts.csv")

# Confirm final topic distribution

print("Total rows:", len(df))

topic_counts = df["topic_prediction"].value_counts()
display(topic_counts)

topic_counts.to_csv(
    "/content/round3_final_topic_counts.csv"
)

print("Saved: /content/round3_final_topic_counts.csv")

import pandas as pd
import matplotlib.pyplot as plt

# Prepare publication date and sentiment columns
df["published_at"] = pd.to_datetime(
    df["published_at"], errors="coerce", utc=True
)

df["publication_date"] = df["published_at"].dt.date

# Exclude invalid / placeholder dates from this chart
plot_df = df[
    df["published_at"].notna() &
    (df["published_at"] >= "2000-01-01")
].copy()

# Count each sentiment by publication date
daily_sentiment = (
    plot_df.groupby(["publication_date", "sentiment_prediction"])
    .size()
    .unstack(fill_value=0)
)

# Plot daily sentiment counts
daily_sentiment.plot(
    kind="line",
    marker="o",
    figsize=(14, 6)
)

plt.title("Daily Sentiment Distribution in Collected News")
plt.xlabel("Publication Date")
plt.ylabel("Number of Articles")
plt.xticks(rotation=45)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Save chart data
daily_sentiment.to_csv(
    "/content/round3_daily_sentiment.csv"
)

print("Saved: /content/round3_daily_sentiment.csv")

# Show example articles for each predicted topic

for topic in df["topic_prediction"].dropna().unique():
    print("\nTOPIC:", topic)

    examples = df.loc[
        df["topic_prediction"] == topic,
        ["title", "source", "published_at"]
    ].head(3)

    display(examples)

# Save examples for the report
topic_examples = (
    df.groupby("topic_prediction", group_keys=False)
      .head(3)[["topic_prediction", "title", "source", "published_at"]]
)

topic_examples.to_csv(
    "/content/round3_topic_examples.csv",
    index=False
)

print("Saved: /content/round3_topic_examples.csv")

import pandas as pd

# Convert publication timestamps
df["published_at"] = pd.to_datetime(
    df["published_at"], errors="coerce", utc=True
)

# Keep valid publication dates for activity analysis
activity_df = df[
    df["published_at"].notna() &
    (df["published_at"] >= "2000-01-01")
].copy()

activity_df["publication_date"] = (
    activity_df["published_at"].dt.date
)

# Count articles per publication date
daily_activity = (
    activity_df.groupby("publication_date")
    .size()
    .reset_index(name="article_count")
    .sort_values("publication_date")
)

display(daily_activity)

# Show busiest publication date
busiest = daily_activity.loc[
    daily_activity["article_count"].idxmax()
]

print("Busiest date:", busiest["publication_date"])
print("Articles that date:", busiest["article_count"])

# Save results
daily_activity.to_csv(
    "/content/round3_daily_activity.csv",
    index=False
)

print("Saved: /content/round3_daily_activity.csv")

import pandas as pd

df = pd.read_csv("/content/round3_analyzed_news.csv")

# Convert publication and collection times
df["published_at"] = pd.to_datetime(
    df["published_at"], errors="coerce", utc=True
)
df["collected_at"] = pd.to_datetime(
    df["collected_at"], errors="coerce", utc=True
)

# Count articles by publication date
df["publication_date"] = df["published_at"].dt.date

daily_activity = (
    df.dropna(subset=["publication_date"])
      .groupby("publication_date")
      .size()
      .reset_index(name="article_count")
      .sort_values("publication_date")
)

print("Daily article activity:")
display(daily_activity)

# Check collection time span
print("\nCollection start:", df["collected_at"].min())
print("Collection end:", df["collected_at"].max())

# Save activity summary
daily_activity.to_csv(
    "/content/round3_daily_activity.csv",
    index=False
)

print("\nSaved: round3_daily_activity.csv")

import pandas as pd

# Load the already analyzed dataset
df = pd.read_csv("/content/round3_analyzed_news.csv")

# Convert publication time to datetime
df["published_at"] = pd.to_datetime(
    df["published_at"], errors="coerce", utc=True
)

# Remove rows where publication time is missing
valid_df = df.dropna(subset=["published_at"]).copy()

# Get the publication date
valid_df["publication_date"] = (
    valid_df["published_at"].dt.date
)

# Count articles published each day
daily_activity = (
    valid_df.groupby("publication_date")
    .size()
    .reset_index(name="article_count")
    .sort_values("publication_date")
)

# Display and save the result
display(daily_activity)

daily_activity.to_csv(
    "/content/round3_daily_activity.csv",
    index=False
)

print("Saved: /content/round3_daily_activity.csv")

import feedparser
import pandas as pd
from datetime import datetime, timezone
from urllib.parse import quote
from pathlib import Path

# Record the time of this collection
snapshot_time = datetime.now(timezone.utc).isoformat()

# Use the same topics as the original collection
topics = {
    "cybercrime": '"cybercrime" OR "online fraud" OR "digital scam"',
    "digital_exclusion": '"digital exclusion" OR "digital divide" OR "internet access"'
}

rows = []

# Collect fresh articles from Google News RSS
for category, query in topics.items():
    url = (
        "https://news.google.com/rss/search?q="
        + quote(query)
        + "&hl=en-IN&gl=IN&ceid=IN:en"
    )

    feed = feedparser.parse(url)

    for entry in feed.entries:
        rows.append({
            "title": entry.get("title", ""),
            "summary": entry.get("summary", ""),
            "url": entry.get("link", ""),
            "published_at": entry.get("published", ""),
            "collected_at": snapshot_time,
            "snapshot_time": snapshot_time,
            "source": entry.get("source", {}).get("title", ""),
            "search_category": category
        })

# Create a DataFrame from the new collection
new_df = pd.DataFrame(rows)

# Clean the new data
if not new_df.empty:
    new_df = new_df.drop_duplicates(subset=["url"])
    new_df["title"] = new_df["title"].fillna("").astype(str).str.strip()
    new_df["summary"] = new_df["summary"].fillna("").astype(str)
    new_df = new_df[new_df["title"] != ""].copy()

    # Prepare text for the Round 2 models
    new_df["analysis_text"] = (
        new_df["title"] + " " + new_df["summary"]
    ).str.strip()

    # Apply the already loaded Round 2 models
    new_df["sentiment_prediction"] = sentiment_model.predict(
        new_df["analysis_text"]
    )
    new_df["topic_prediction"] = topic_model.predict(
        new_df["analysis_text"]
    )

    # Save this snapshot separately
    output_path = Path("/content/round3_new_snapshot.csv")
    new_df.to_csv(output_path, index=False, encoding="utf-8-sig")

    print("New articles collected:", len(new_df))
    print("Snapshot time (UTC):", snapshot_time)
    print("Saved to:", output_path)

else:
    print("No articles returned by the RSS feeds.")

import pandas as pd

df1 = pd.read_csv(
    "/content/DATA_VORTEX_R3_news_dataset_1.csv"
)
df2 = pd.read_csv(
    "/content/DATA_VORTEX_R3_news_dataset_2.csv"
)

print("===== DATASET 1: COLUMN NAMES =====")
print(df1.columns.tolist())
display(df1.head(3))

print("\n===== DATASET 2: COLUMN NAMES =====")
print(df2.columns.tolist())
display(df2.head(3))

# Runtime mein loaded model/pipeline variables dhoondo
from sklearn.pipeline import Pipeline

for name, obj in globals().copy().items():
    if isinstance(obj, Pipeline):
        print(name, "->", type(obj).__name__)

import pandas as pd
from pathlib import Path

# Exact filenames you gave
file1 = "/content/DATA_VORTEX_R3_news_dataset_1.csv"
file2 = "/content/DATA_VORTEX_R3_news_dataset_2.csv"

def analyze_csv(file_path):
    df = pd.read_csv(file_path)

    # Prepare text for the Round 2 models
    df["analysis_text"] = (
        df["title"].fillna("").astype(str) + " " +
        df["summary"].fillna("").astype(str)
    ).str.strip()

    # Apply the loaded pipelines
    df["sentiment_prediction"] = sentiment_model.predict(
        df["analysis_text"]
    )
    df["topic_prediction"] = topic_model.predict(
        df["analysis_text"]
    )

    # Save analyzed copy; raw CSV remains unchanged
    output_path = file_path.replace(".csv", "_analyzed.csv")
    df.to_csv(output_path, index=False)

    print(f"\nAnalyzed: {Path(file_path).name}")
    print("Rows:", len(df))
    print("\nSentiment counts:")
    print(df["sentiment_prediction"].value_counts(dropna=False))
    print("\nTopic counts:")
    print(df["topic_prediction"].value_counts(dropna=False))
    print("\nSaved:", output_path)

    return df

df1 = analyze_csv(file1)
df2 = analyze_csv(file2)

print("DATASET 1 vs DATASET 2")
print("=" * 40)

print("\n1. Article counts")
print("Dataset 1:", len(df1))
print("Dataset 2:", len(df2))

print("\n2. Sentiment comparison")
sentiment_comparison = pd.concat(
    [
        df1["sentiment_prediction"].value_counts().rename("Dataset 1"),
        df2["sentiment_prediction"].value_counts().rename("Dataset 2")
    ],
    axis=1
).fillna(0).astype(int)

display(sentiment_comparison)

print("\n3. Topic comparison")
topic_comparison = pd.concat(
    [
        df1["topic_prediction"].value_counts().rename("Dataset 1"),
        df2["topic_prediction"].value_counts().rename("Dataset 2")
    ],
    axis=1
).fillna(0).astype(int)

display(topic_comparison)

print("\n4. URL overlap")
urls1 = set(df1["url"].dropna().astype(str))
urls2 = set(df2["url"].dropna().astype(str))

common_urls = urls1.intersection(urls2)
print("Common URLs:", len(common_urls))
print("Unique to Dataset 1:", len(urls1 - urls2))
print("Unique to Dataset 2:", len(urls2 - urls1))

import os
print(os.listdir("/content"))

# Compare sentiment percentages
sentiment_pct = pd.concat([
    df1["sentiment_prediction"].value_counts(normalize=True).mul(100).rename("Dataset 1 (%)"),
    df2["sentiment_prediction"].value_counts(normalize=True).mul(100).rename("Dataset 2 (%)")
], axis=1).fillna(0).round(2)

display(sentiment_pct)

# Compare topic percentages
topic_pct = pd.concat([
    df1["topic_prediction"].value_counts(normalize=True).mul(100).rename("Dataset 1 (%)"),
    df2["topic_prediction"].value_counts(normalize=True).mul(100).rename("Dataset 2 (%)")
], axis=1).fillna(0).round(2)

display(topic_pct)

# Duplicate/overlap check
urls1 = set(df1["url"].dropna().astype(str))
urls2 = set(df2["url"].dropna().astype(str))

print("Shared URLs:", len(urls1 & urls2))
print("Dataset 1 unique URLs:", len(urls1 - urls2))
print("Dataset 2 unique URLs:", len(urls2 - urls1))

# Parse timestamps
for df in [df1, df2]:
    df["published_at"] = pd.to_datetime(
        df["published_at"], errors="coerce", utc=True
    )
    df["collected_at"] = pd.to_datetime(
        df["collected_at"], errors="coerce", utc=True
    )

def show_time_summary(df, name):
    print(f"\n{name}")
    print("Rows:", len(df))
    print("Published range:",
          df["published_at"].min(), "to", df["published_at"].max())
    print("Collected range:",
          df["collected_at"].min(), "to", df["collected_at"].max())
    print("Distinct collection timestamps:",
          df["collected_at"].nunique())
    print("Missing published_at:", df["published_at"].isna().sum())
    print("Missing collected_at:", df["collected_at"].isna().sum())

show_time_summary(df1, "DATASET 1")
show_time_summary(df2, "DATASET 2")

shared = df1[["url", "collected_at"]].merge(
    df2[["url", "collected_at"]],
    on="url",
    how="inner",
    suffixes=("_1", "_2")
)

shared["collection_gap_hours"] = (
    shared["collected_at_2"] - shared["collected_at_1"]
).dt.total_seconds() / 3600

print("Shared articles:", len(shared))
print("Different collection timestamps:",
      (shared["collection_gap_hours"] != 0).sum())
print("Median collection gap (hours):",
      shared["collection_gap_hours"].median())

display(shared.head(10))

shared = df1[["url", "collected_at"]].merge(
    df2[["url", "collected_at"]],
    on="url",
    how="inner",
    suffixes=("_1", "_2")
)

shared["gap_hours"] = (
    shared["collected_at_2"] - shared["collected_at_1"]
).dt.total_seconds() / 3600

print("Shared URLs:", len(shared))
print("Same collection time:",
      (shared["gap_hours"] == 0).sum())
print("Different collection time:",
      (shared["gap_hours"] != 0).sum())
print("Median gap (hours):", shared["gap_hours"].median())
print("Min gap (hours):", shared["gap_hours"].min())
print("Max gap (hours):", shared["gap_hours"].max())

display(shared.head(10))

import pandas as pd

# Preserve which batch each article came from
a = df1.copy()
b = df2.copy()

a["batch"] = "Dataset 1"
b["batch"] = "Dataset 2"

combined = pd.concat([a, b], ignore_index=True)

# Flag suspicious Unix-epoch publication dates
combined["published_at"] = pd.to_datetime(
    combined["published_at"], errors="coerce", utc=True
)

combined["date_quality"] = "OK"
combined.loc[
    combined["published_at"].isna(),
    "date_quality"
] = "Missing/Invalid"

combined.loc[
    combined["published_at"].dt.year.eq(1970),
    "date_quality"
] = "Suspicious 1970 date"

# Count batch appearances for each URL
batch_info = (
    combined.groupby("url")["batch"]
    .agg(lambda x: ", ".join(sorted(set(x))))
    .rename("appeared_in")
)

# Keep the latest collected copy for each URL
combined = combined.sort_values("collected_at")
clean_df = combined.drop_duplicates(subset="url", keep="last").copy()

clean_df = clean_df.merge(
    batch_info,
    left_on="url",
    right_index=True,
    how="left"
)

# Save cleaned dataset
output_file = "/content/DATA_VORTEX_R3_combined_clean.csv"
clean_df.to_csv(output_file, index=False)

print("Original total rows:", len(df1) + len(df2))
print("Unique URLs after deduplication:", clean_df["url"].nunique())
print("Rows in clean dataset:", len(clean_df))
print("\nBatch overlap:")
print(clean_df["appeared_in"].value_counts())

print("\nPublication date quality:")
print(clean_df["date_quality"].value_counts())

print("\nSaved:", output_file)

import pandas as pd

df = pd.read_csv("/content/DATA_VORTEX_R3_combined_clean.csv")

# Sentiment distribution
print("SENTIMENT COUNTS")
display(df["sentiment_prediction"].value_counts().to_frame("Articles"))

print("\nSENTIMENT PERCENTAGES")
display(
    df["sentiment_prediction"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .to_frame("Percent")
)

# Topic distribution
print("\nTOPIC COUNTS")
display(df["topic_prediction"].value_counts().to_frame("Articles"))

# Top news sources
print("\nTOP 10 SOURCES")
display(df["source"].value_counts().head(10).to_frame("Articles"))

# Batch distribution by sentiment
print("\nSENTIMENT BY BATCH")
display(pd.crosstab(df["appeared_in"], df["sentiment_prediction"]))

# Publication date quality
print("\nDATE QUALITY")
display(df["date_quality"].value_counts().to_frame("Rows"))

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/DATA_VORTEX_R3_combined_clean.csv")

# 1. Sentiment distribution
sentiment_counts = df["sentiment_prediction"].value_counts()

plt.figure(figsize=(7, 5))
sentiment_counts.plot(kind="bar")
plt.title("Sentiment Distribution (234 Unique News Articles)")
plt.xlabel("Predicted Sentiment")
plt.ylabel("Number of Articles")
plt.xticks(rotation=0)
plt.tight_layout()
plt.savefig("/content/R3_sentiment_distribution.png", dpi=200)
plt.show()

# 2. Topic distribution
topic_counts = df["topic_prediction"].value_counts()

plt.figure(figsize=(8, 5))
topic_counts.plot(kind="bar")
plt.title("Predicted Topic Distribution")
plt.xlabel("Predicted Topic")
plt.ylabel("Number of Articles")
plt.xticks(rotation=25, ha="right")
plt.tight_layout()
plt.savefig("/content/R3_topic_distribution.png", dpi=200)
plt.show()

# 3. Top 10 sources
source_counts = df["source"].value_counts().head(10).sort_values()

plt.figure(figsize=(9, 6))
source_counts.plot(kind="barh")
plt.title("Top 10 News Sources")
plt.xlabel("Number of Articles")
plt.ylabel("Source")
plt.tight_layout()
plt.savefig("/content/R3_top_sources.png", dpi=200)
plt.show()

print("Saved 3 charts in /content/")

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/DATA_VORTEX_R3_combined_clean.csv")

df["published_at"] = pd.to_datetime(
    df["published_at"], errors="coerce", utc=True
)

# Exclude invalid/epoch publication dates from time-based analysis
valid = df[
    df["published_at"].notna() &
    (df["published_at"].dt.year > 1970)
].copy()

valid["published_hour"] = valid["published_at"].dt.floor("h")

hourly = (
    valid.groupby("published_hour")
    .size()
    .sort_index()
)

print("Valid articles for publication-time analysis:", len(valid))
print("Excluded suspicious/invalid dates:", len(df) - len(valid))
print("\nTop 10 publication hours:")
display(hourly.sort_values(ascending=False).head(10).to_frame("Article count"))

plt.figure(figsize=(12, 5))
hourly.plot(kind="line", marker="o")
plt.title("News Publication Activity by Hour")
plt.xlabel("Publication hour (UTC)")
plt.ylabel("Number of articles")
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("/content/R3_hourly_publication_activity.png", dpi=200)
plt.show()

import os
import pandas as pd

files = [
    "/content/DATA_VORTEX_R3_combined_clean.csv",
    "/content/R3_sentiment_distribution.png",
    "/content/R3_topic_distribution.png",
    "/content/R3_top_sources.png",
    "/content/R3_hourly_publication_activity.png"
]

print("FINAL FILE CHECK")
for f in files:
    print(("✅ " if os.path.exists(f) else "❌ "), os.path.basename(f))

df = pd.read_csv(files[0])

print("\nDataset rows:", len(df))
print("Sentiment labels:", df["sentiment_prediction"].value_counts().to_dict())
print("Topic labels:", df["topic_prediction"].value_counts().to_dict())

!pip -q install reportlab

from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

pdf_path = "/content/DATA_VORTEX_R3_Final_Report.pdf"

doc = SimpleDocTemplate(
    pdf_path,
    pagesize=A4,
    rightMargin=45, leftMargin=45,
    topMargin=45, bottomMargin=45
)

styles = getSampleStyleSheet()
story = []

story.append(Paragraph(
    "DATA VORTEX A'26 — Round 3",
    styles["Title"]
))
story.append(Paragraph(
    "Public Reaction to a Trending Social Issue",
    styles["Heading2"]
))
story.append(Paragraph(
    "Focus: Cybercrime and Digital Exclusion",
    styles["Normal"]
))
story.append(Spacer(1, 16))

sections = [
    ("1. Data Collection Method",
     "News articles were collected using Google News RSS in two batches. "
     "The dataset includes article titles, summaries, URLs, publication "
     "timestamps, collection timestamps, sources, and search categories. "
     "Round 2 sentiment and topic pipelines were applied to article text."),

    ("2. Time Window",
     "Dataset 1 was collected around 2026-09-21 02:59:38 UTC. "
     "Dataset 2 was collected around 2026-09-21 07:48:20 UTC. "
     "The median collection-time gap among 166 shared URLs was "
     "approximately 4.812 hours. The batches are overlapping collections, "
     "not independent social-media snapshots."),

    ("3. Sentiment Analysis",
     "After URL deduplication, 234 unique articles remained. "
     "Predicted sentiment: Neutral 211 (90.17%), Negative 20 (8.55%), "
     "Positive 3 (1.28%). These are model predictions on news text, "
     "not direct measurements of public sentiment."),

    ("4. Activity Analysis",
     "The dataset contains 400 raw rows across two batches and 234 unique "
     "URLs after deduplication. Article collection volume is not equivalent "
     "to likes, comments, shares, or social engagement. No verified "
     "engagement spike can be established from these fields."),

    ("5. Topic and Entity Analysis",
     "Predicted topics: Community_Discussion 230 (98.29%), "
     "Technical_Issues 2, Account_Security 1, and Feature_Feedback 1. "
     "The high concentration in one predicted class should be interpreted "
     "cautiously and may reflect model-label limitations."),

    ("6. Trigger Explanations",
     "The available data does not establish two sentiment shifts or causal "
     "triggers. News themes may provide context, but without social "
     "interaction data and multiple validated time-series observations, "
     "they cannot be treated as confirmed causes."),

    ("7. Data Quality and Limitations",
     "Two records contain suspicious publication timestamps at "
     "1970-01-01 and were flagged. The dataset is news-based, has substantial "
     "URL overlap between batches, and uses model-generated labels. "
     "Results should not be generalized as direct measures of social-media "
     "public reaction.")
]

for heading, text in sections:
    story.append(Paragraph(heading, styles["Heading2"]))
    story.append(Paragraph(text, styles["BodyText"]))
    story.append(Spacer(1, 10))

story.append(Paragraph(
    "Dataset summary",
    styles["Heading2"]
))

table_data = [
    ["Metric", "Result"],
    ["Raw rows", "400"],
    ["Unique URLs after deduplication", "234"],
    ["URLs in both batches", "166"],
    ["Dataset 1 only", "34"],
    ["Dataset 2 only", "34"],
    ["Suspicious 1970 dates", "2"],
]

table = Table(table_data, colWidths=[3.4*inch, 2.2*inch])
table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
    ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
    ("PADDING", (0,0), (-1,-1), 6),
]))
story.append(table)

doc.build(story)

print("PDF saved:", pdf_path)

